image: registry.gitlab.com/dev4754101/inventorycentral/build-agent:1.0.0

stages:
  - deploy

deploy-job:
  stage: deploy
  variables:
    AWS_REGION: us-east-1  # or your preferred region
  script:
    - echo "$CI_JOB_JWT_V2" > /tmp/web_identity_token
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token
    - export AWS_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/GitLab-OIDC-CDK-ROLE"
    - aws sts get-caller-identity
    - cdk list --require-approval never