name: Destroy

on:
  workflow_dispatch: # Manual trigger 

env:
  AWS_PRIMARY_REGION: "us-east-1"
  AWS_DOMAIN_NAME: "dungeondivinelabs.com"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_PRIMARY_REGION }}
      - name: Debug AWS Environment Variables
        run: |
          echo "CDK_DEFAULT_ACCOUNT: $CDK_DEFAULT_ACCOUNT"
          echo "CDK_DEFAULT_REGION: $CDK_DEFAULT_REGION"
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          npm install -g aws-cdk
      - run: make destroy